### ISSUE TITLE
.gitignore for this project for build files.

### ISSUE THREAD

**Issue by RyanDawkins** [TeamGreenMobileApp2015/Introductory-Team-Project-Simon#1]
We just need to add the .gitignore, git rm *, and git add .

That will enforce our ignore.

**Comment by nathan-hoover** [comment]
I added the Swift specific .gitignore from   https://github.com/github/gitignore. You should be able to add any/modify any other file in the project since I gave you and are other team members owner status.

**Comment by RyanDawkins** [comment]
I just rm'd and added everything back to the project so it removed any project files that may have existed. https://github.com/TeamBlueMobileApp2015/Introductory-Team-Project-Simon/commit/104b151dd9aad2b16e77e6894e528a6f1dc0753a

**Comment by RyanDawkins** [comment]
Totally screwed that up. I'm going to reset the head back and fix that..

**Comment by RyanDawkins** [comment]
Fixed it... Sorry I totally messed it up.
