### ISSUE TITLE
We need gameplay sounds!

### ISSUE THREAD

**Issue by RyanDawkins** [TeamGreenMobileApp2015/Introductory-Team-Project-Simon#5]

**Comment by JordanFest** [comment]
I have some minor experience with sound effects. I need a list of important SFX that we need for the project.

**Comment by RyanDawkins** [comment]
I doubt we need original sounds for this game. I wouldn't prioritize this because it would probably be more time consuming than what is really needed. I think the purpose is we just need to "play a sound" opposed to really add some great feature to it. @JordanFest
