### ISSUE TITLE
Could not load the "YellowButtonPressedV2" image referenced

### ISSUE THREAD

**Issue by nathan-hoover** [TeamGreenMobileApp2015/Introductory-Team-Project-Simon#7]
2015-09-14 23:39:52.823 Introductory-Team-Project-Simon[8098:288216] Could not load the "YellowButtonPressedV2" image referenced from a nib in the bundle with identifier "TeamBlue.Introductory-Team-Project-Simon"

Too tired to fix tonight

**Comment by JordanFest** [comment]
I can't review the code tonight, but, you could check to make sure that the specified image is in the assets of the project. It's possible that the reference to the image was from an external source, but, I can't be sure.

**Comment by nathan-hoover** [comment]
It is showing the image on the file system without problem. Hopefully this is an easy fix that I am just overlooking.

**Comment by nathan-hoover** [comment]
Fixed by changing the name to YellowButtonPressedV2 in all code.
